-- Warning: Generated by IPC system do not edit manually!
return {
  ["replies"] = {},
  ["messages"] = {},
  ["methods"] = {
    [1] = "core.change_directory(directory: string)",
    [2] = "core.open_directory(directory: string)",
    [3] = "core.open_file(file: string)"
  },
  ["primary"] = true,
  ["signals"] = {
    [1] = "core.tab_drag_received(file: string)",
    [2] = "core.tab_drag_start(file: string)",
    [3] = "core.tab_drag_stop()"
  },
  ["id"] = "15848",
  ["position"] = 1,
  ["last_update"] = 1700829752
}